services:
  - type: web
    name: datacollect-backend
    runtime: python
    buildCommand: pip install -r backend/requirements-prod.txt
    startCommand: cd backend && uvicorn app_prod:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql+asyncpg://postgres:NJtz24HYFr9JNrNK@db.qsuemkbonmgfufpcscua.supabase.co:5432/postgres
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
    plan: free
    region: oregon
    
  - type: static
    name: datacollect-frontend
    buildCommand: cd frontend && npm ci --legacy-peer-deps && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://datacollect-cameroun-prod.onrender.com
    plan: free
    region: oregon

